name: axalta
description: An example of JWT authentication with flutter.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  equatable: ^2.0.0
  http: ^1.1.0
  flutter_form_builder: ^9.0.0
  form_builder_validators: ^9.0.0
  mask_text_input_formatter: ^2.1.0
  jwt_decoder: ^2.0.1
  flutter_secure_storage: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
